### PR TITLE
Add wg-policy whitepaper into the sig-security repo

### PR DESCRIPTION
**Pull request by rficcaglia**
This is the work from the Policy WG and reviewers. Refer to WG meeting notes for history: https://docs.google.com/document/d/1ihFfEfgViKlUMbY2NKxaJzBkgHh-Phk5hqKTzK-NEEs/edit#

### CODE REVIEW

**Comment by JimBugwadia** [comment]
@rficcaglia - we can close this PR. The updated paper is now merged at: https://github.com/kubernetes/sig-security/tree/main/sig-security-docs/papers/policy.

**Comment by JimBugwadia** [comment]
@PushkarJ - yes, this PR can be closed. Thanks!

**Comment by PushkarJ** [comment]
/lifecycle rotten 

(To see if the bot closes this after this label is added)

**Comment by JimBugwadia** [comment]
Hi @rficcaglia can you please try adding a `\close` via @rficcaglia instead of @sunstonesecure-robert? That should work!

**Pull request closed without merging**
