### PR TITLE
Moved scanning script from test-infra to security-tooling

### PR DESCRIPTION
**Pull request by Dylan-G-Roberts**
First PR for https://github.com/kubernetes/sig-security/issues/60

Just moving the file over, next step is calling it as outlined here: https://github.com/kubernetes/sig-security/pull/61#issuecomment-1238311036

### CODE REVIEW

**Comment by tabbysable** [comment]
Diffed this locally against the version from https://github.com/kubernetes/test-infra/pull/33817 and it all matches.

/approve

**Comment by smarticu5** [comment]
I've also checked against https://github.com/kubernetes/test-infra/pull/33817/files, and happy that it matches.

/lgtm

**Review by smarticu5 — APPROVED** [review]

**Comment by smarticu5** [comment]
Now that I've approved a change, can I add the label? 

(Apologies for potential update spam, I'm learning in public here) 

/lgtm

**Review by mtardy — APPROVED** [review]
I trust those two nice people manually checking!

/lgtm

**Pull request merged**
