### PR TITLE
Add draft report from Adalogics fuzzing efforts

### PR DESCRIPTION
**Pull request by tabbysable**
Adalogics engaged in contract work with LF to fuzz Kubernetes; this is the draft of their report of the experience and results.

### CODE REVIEW

**Comment by reylejano** [comment]
/lgtm
feel free to remove the hold when there is a newer draft or final version

**Review by DavidKorczynski — APPROVED** [review]
LGTM

**Comment by DavidKorczynski** [comment]
@tabbysable @reylejano  @IanColdwater any updates on this? It would be nice to get this merged

**Pull request merged**
