### PR TITLE
add missing images for K8s Policy paper

### PR DESCRIPTION
**Pull request by JimBugwadia**
Signed-off-by: Jim Bugwadia <jim@nirmata.com>

I had missed moving the images folder! Added and re-generated the PDF.

### CODE REVIEW

**Comment by JimBugwadia** [comment]
Hi @PushkarJ and @savitharaghunathan - apologies I missed this in the prior PR!

**Review by savitharaghunathan — COMMENTED** [review]
Thanks @JimBugwadia 
/lgtm

**Review by savitharaghunathan — COMMENTED** [review]
/approve

**Pull request merged**
