### PR TITLE
move script from test-infra to sig-security

### LINKED ISSUE #60: Move Snyk Scripts from k/test-infra to k/sig-security/sig-security-tooling
As we learnt from https://github.com/kubernetes/test-infra/pull/26896#discussion_r932628360 it is possible for prow to pick up shell scripts outside of `k/test-infra`.

Moving the script that is present here: https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-k8s-infra/trusted/sig-security-trusted.yaml#L29-L87 into a dedicated shell script with name `build-deps-and-release-images.sh` under `k/sig-security/sig-security-tooling/scanning` would be great for faster iteration and approvals and reviews can be managed within SIG Security members. 

/sig security
/good-first-issue
/help

### PR DESCRIPTION
**Pull request by lakshya8066**
Fixes #60 
Moved shell script from https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-k8s-infra/trusted/sig-security-trusted.yaml#L29-L87 to k/sig-security/sig-security-tooling/scanning.

### CODE REVIEW

**Comment by PushkarJ** [comment]
Thank you @lakshya8066 . We will need a peer PR on `k/test-infra` too to ensure this script gets called out. 

Using this block as reference: https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-k8s-infra/trusted/sig-security-trusted.yaml#L97-L114 can come up with a draft PR that would execute this script ?

I will hold this PR until then to ensure we can merge both these PRs together!

/hold

**Comment by lakshya8066** [comment]
Hi @PushkarJ I have made a draft PR but don't feel confident about the implementation. 
If there are corrections to be made, I will be happy to learn about it and edit the PR.

**Review by maheshkasabe — APPROVED** [review]

**Comment by tabbysable** [comment]
@lakshya8066 @PushkarJ

Would you two prefer to update this PR to match the current state of the script that is inline in https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-k8s-infra/trusted/sig-security-trusted.yaml?

Or would you prefer to close this one and start a new one?

**Comment by PushkarJ** [comment]
@tabbysable sorry for the late response. With the upcoming changes because of https://github.com/kubernetes/sig-security/issues/95 it might make sense to close this PR for now and then revisit it at a later date

Please re-open if you disagree :)

/close

**Pull request closed without merging**
